// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAL2oMpdpYi4pZDhKN6WYgPWw5kGz52icI',
    appId: '1:996908628595:web:fbbdcc6128bb21f63b4806',
    messagingSenderId: '996908628595',
    projectId: 'notification-flutter-13fc0',
    authDomain: 'notification-flutter-13fc0.firebaseapp.com',
    storageBucket: 'notification-flutter-13fc0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCf4BTqwJLn1TcbFRYvcVeqvpj3zgdpkuM',
    appId: '1:996908628595:android:f79951870781b26d3b4806',
    messagingSenderId: '996908628595',
    projectId: 'notification-flutter-13fc0',
    storageBucket: 'notification-flutter-13fc0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJMP--fSk4CLfBcg_mA2UgVBshje6I37k',
    appId: '1:996908628595:ios:4f6020aa3690e8bc3b4806',
    messagingSenderId: '996908628595',
    projectId: 'notification-flutter-13fc0',
    storageBucket: 'notification-flutter-13fc0.firebasestorage.app',
    iosBundleId: 'com.example.localPushNotificationsFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJMP--fSk4CLfBcg_mA2UgVBshje6I37k',
    appId: '1:996908628595:ios:4f6020aa3690e8bc3b4806',
    messagingSenderId: '996908628595',
    projectId: 'notification-flutter-13fc0',
    storageBucket: 'notification-flutter-13fc0.firebasestorage.app',
    iosBundleId: 'com.example.localPushNotificationsFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAL2oMpdpYi4pZDhKN6WYgPWw5kGz52icI',
    appId: '1:996908628595:web:4e35ce3e21a5578e3b4806',
    messagingSenderId: '996908628595',
    projectId: 'notification-flutter-13fc0',
    authDomain: 'notification-flutter-13fc0.firebaseapp.com',
    storageBucket: 'notification-flutter-13fc0.firebasestorage.app',
  );

}